name: Scene Detector v4a

run-name: "ScDetect - ${{ inputs.ShowName }} @ ${{ inputs.EpLabels }}"

on:
  workflow_dispatch:
    inputs:
      ShowName:
        description: "Anime/Movie/Show Name, @VapourCoderZ4a_Hash/x01.showList.txt"
        required: true
        type: string
      EpLabels:
        description: "One/Multiple EpLabel, `+`-separated, S0[0-9]E[0-9][0-9] / EpFull"
        required: true
        type: string
        default: "S01E01"
      CustomEnvs:
        description: "Env Overrides (pipe-separated), x=someVal / minSCLenth=36 / QuickExit=1 / Probe=false / SCDebug=true"
        type: string
        required: false
      CleanWS:
        description: "Clean Workspaces with slimhub_actions"
        type: boolean
        default: false
        required: false

env:
  SCDETECT: "true"
  ShowName: ${{ github.event.inputs.ShowName }}
  EpLabels: ${{ github.event.inputs.EpLabels }}
  CustomEnvs: ${{ github.event.inputs.CustomEnvs }}
  VapourScriptAddr: "https://gist.github.com/rokibhasansagar/${{ secrets.VapourCoderZ4a_Hash }}"
  RCLONE_CONFIG_HASH: ${{ secrets.RCLONE_CONFIG_HASH }}

jobs:
  scdetect:
    name: "SCDetector"
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'main'
      - name: GitHub Auth
        uses: rokibhasansagar/custom_workflows/git_config@main
        with:
          credential: "yes"
          git_cookies: "no"
        env:
          PAT: ${{ secrets.GH_TOKEN }}
      - name: Clean Workspace with slimhub_actions
        if: github.event.inputs.CleanWS == 'true'
        uses: rokibhasansagar/slimhub_actions@main
        with:
          retain: "docker_buildkit"
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Custom Env Patcher
        if: github.event.inputs.CustomEnvs != ''
        run: |
          # Prepare Custom Env Var Overrides
          if [[ ${CustomEnvs} != '' ]]; then
            for i in $(sed 's/|/\n/g' <<<"${CustomEnvs}"); do
              v=$(awk -F'=' '{print $1}' <<<"${i}")
              w=$(cut -d'=' -f2- <<<"${i}" | sed 's#"##g')
              echo "$v=$w" >>$GITHUB_ENV
            done
          fi
          unset v w 2>/dev/null || true
      - name: Run SCDetect Script
        run: |
          # Execute Script Stealthly
          eval 'set -eo pipefail' 2>/dev/null
          eval 'set +o history' 2>/dev/null
          export latestRevision=$(git ls-remote -q "${VapourScriptAddr}" HEAD | awk '{print $1}')
          echo -e "latestRevision == ${latestRevision}\n"
          for sc in x99.scriptPatcher.sh x07.testContainer.sh x09.sceneDetector.sh x13.filterGen.sh; do
            curl -sL --retry 5 --retry-connrefused "${VapourScriptAddr}/raw/${latestRevision}/${sc}" -O
          done
          source ${GITHUB_WORKSPACE}/x99.scriptPatcher.sh && rm ${GITHUB_WORKSPACE}/x99.scriptPatcher.sh
          source ${GITHUB_WORKSPACE}/x09.sceneDetector.sh || exit 1
          eval 'set -o history' 2>/dev/null

